/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    AudioPlayer: typeof import('./components/audioPlayer.vue')['default']
    Cursor: typeof import('./components/Cursor.vue')['default']
    FollowCursor: typeof import('./components/FollowCursor.vue')['default']
    FrostedGlassPanel: typeof import('./components/FrostedGlassPanel.vue')['default']
    Login: typeof import('./components/Login.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sakura: typeof import('./components/Sakura.vue')['default']
    SilderAlert: typeof import('./components/silderAlert.vue')['default']
  }
}
