name: compile and deploy github page

on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout 仓库源码
        uses: actions/checkout@v4

      - name: 准备编译环境  
        run: |
          sudo apt-get update
          sudo apt-get install -y nodejs
          npm -v

      - name: 安装编译依赖
        run: npm install
        
      - name: 编译项目
        run: |
          pwd
          npm run build

      - name: 查看 dist 文件夹
        run: |
            ls dist/
